-- Mentor-voice artifact, 1:1 with a phase_evaluation. Generated by a
-- separate LLM call after the evaluator. Output is plain Markdown prose
-- (no schema validation); the LLM has freedom over structure within
-- the section conventions described in the prompt.
--
-- The mentor call is best-effort — failures don't propagate up to the
-- eval HTTP response, and missing rows here are expected when an LLM
-- call errored or was rate-limited.

CREATE TABLE "mentor_artifacts" (
    "id" UUID NOT NULL,
    "phase_evaluation_id" UUID NOT NULL,
    "content" TEXT NOT NULL,
    "model_used" TEXT NOT NULL,
    "tokens_in" INTEGER NOT NULL,
    "tokens_out" INTEGER NOT NULL,
    "cache_read_tokens" INTEGER NOT NULL DEFAULT 0,
    "cache_creation_tokens" INTEGER NOT NULL DEFAULT 0,
    "latency_ms" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "mentor_artifacts_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "mentor_artifacts_phase_evaluation_id_key"
    ON "mentor_artifacts"("phase_evaluation_id");

ALTER TABLE "mentor_artifacts"
    ADD CONSTRAINT "mentor_artifacts_phase_evaluation_id_fkey"
    FOREIGN KEY ("phase_evaluation_id")
    REFERENCES "phase_evaluations"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
